var searchData=
[
  ['delete_0',['Delete',['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_articulo_table_adapter.html#a1bd6ae696f91405fea1ba9896d042eb5',1,'appInvictusStyle.InvictusStyleDataSetTableAdapters.ArticuloTableAdapter.Delete()'],['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_cliente_table_adapter.html#a67ebda23246c48d3a77b642d77a952cb',1,'appInvictusStyle.InvictusStyleDataSetTableAdapters.ClienteTableAdapter.Delete()'],['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_descuento_table_adapter.html#a780d78faf3902afb7d1b3d55e6e90b22',1,'appInvictusStyle.InvictusStyleDataSetTableAdapters.DescuentoTableAdapter.Delete()'],['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_detalle_factura_table_adapter.html#a2a5ac61279067e39f07c10626d08263b',1,'appInvictusStyle.InvictusStyleDataSetTableAdapters.DetalleFacturaTableAdapter.Delete()'],['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_factura_table_adapter.html#a5f28766d81c9eb5101e0f79a2bb10b29',1,'appInvictusStyle.InvictusStyleDataSetTableAdapters.FacturaTableAdapter.Delete()'],['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_provincia_table_adapter.html#a01ca910bf571b5391c2cd52810347e9d',1,'appInvictusStyle.InvictusStyleDataSetTableAdapters.ProvinciaTableAdapter.Delete()'],['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_tipo_cliente_table_adapter.html#aeb9af868bde5ec4d7ea1e00375648769',1,'appInvictusStyle.InvictusStyleDataSetTableAdapters.TipoClienteTableAdapter.Delete()'],['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_tipo_usuario_table_adapter.html#afa5395b199f636cc2e6933a771b9efca',1,'appInvictusStyle.InvictusStyleDataSetTableAdapters.TipoUsuarioTableAdapter.Delete()'],['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_usuario_table_adapter.html#a8807843092e121328579a760a15be778',1,'appInvictusStyle.InvictusStyleDataSetTableAdapters.UsuarioTableAdapter.Delete()']]],
  ['descuentodatatable_1',['DescuentoDataTable',['../classapp_invictus_style_1_1_invictus_style_data_set_1_1_descuento_data_table.html#a7283d4b5bbb71d45b55160dbd62aa0a6',1,'appInvictusStyle.InvictusStyleDataSet.DescuentoDataTable.DescuentoDataTable()'],['../classapp_invictus_style_1_1_invictus_style_data_set_1_1_descuento_data_table.html#abe117c275bd9e76d0df0820fe410c273',1,'appInvictusStyle.InvictusStyleDataSet.DescuentoDataTable.DescuentoDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)']]],
  ['descuentorowchangeevent_2',['DescuentoRowChangeEvent',['../classapp_invictus_style_1_1_invictus_style_data_set_1_1_descuento_row_change_event.html#a2a34c2486bd16108f439cd94ac8f8ff0',1,'appInvictusStyle::InvictusStyleDataSet::DescuentoRowChangeEvent']]],
  ['descuentorowchangeeventhandler_3',['DescuentoRowChangeEventHandler',['../classapp_invictus_style_1_1_invictus_style_data_set.html#a984a906d82092fe6dfc9bc04177a8b63',1,'appInvictusStyle::InvictusStyleDataSet']]],
  ['descuentotableadapter_4',['DescuentoTableAdapter',['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_descuento_table_adapter.html#a4f5975e677dc9acbaca36079ed98dc43',1,'appInvictusStyle::InvictusStyleDataSetTableAdapters::DescuentoTableAdapter']]],
  ['detallefacturadatatable_5',['DetalleFacturaDataTable',['../classapp_invictus_style_1_1_invictus_style_data_set_1_1_detalle_factura_data_table.html#a742910c9b0b8b42ef6aa2d8fdc1b64cb',1,'appInvictusStyle.InvictusStyleDataSet.DetalleFacturaDataTable.DetalleFacturaDataTable()'],['../classapp_invictus_style_1_1_invictus_style_data_set_1_1_detalle_factura_data_table.html#a1bae30c93e8473ea1305960d6f18f179',1,'appInvictusStyle.InvictusStyleDataSet.DetalleFacturaDataTable.DetalleFacturaDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)']]],
  ['detallefacturarowchangeevent_6',['DetalleFacturaRowChangeEvent',['../classapp_invictus_style_1_1_invictus_style_data_set_1_1_detalle_factura_row_change_event.html#abce79c8fafd82ee5f17f5c8c9163ee44',1,'appInvictusStyle::InvictusStyleDataSet::DetalleFacturaRowChangeEvent']]],
  ['detallefacturarowchangeeventhandler_7',['DetalleFacturaRowChangeEventHandler',['../classapp_invictus_style_1_1_invictus_style_data_set.html#a6a0f816ac9bd8cbdc26ee117e96b12e3',1,'appInvictusStyle::InvictusStyleDataSet']]],
  ['detallefacturatableadapter_8',['DetalleFacturaTableAdapter',['../classapp_invictus_style_1_1_invictus_style_data_set_table_adapters_1_1_detalle_factura_table_adapter.html#a50f9ac49cb709ed39072dd2574e89ae2',1,'appInvictusStyle::InvictusStyleDataSetTableAdapters::DetalleFacturaTableAdapter']]]
];
